/* eslint-disable  func-names */
/* eslint-disable max-len */
/* eslint quote-props: ['error', 'consistent']*/
module.exports = {
    'RECIPE_EN_US': {
        'alabama': 'The popular cocktail in Alabama is the Yellowhammers. The Yellowhammer is Gallette’s trademark beverage.',
        'alaska': 'The popular cocktail in Alaska is the Duck Fart. They claim that the "flavors mesh so well together." Just take their word for it.',
        'arizona': 'The popular cocktail in Arizona is the Tequila Sunrise. The OG tequila sunrise originated in Arizona in the 1930\'s.',
	'arkansas': 'The popular cocktail in Arkansas is the Arkansas Razorback. Woo Pig Sooie, if you drink enough of them, they will keep you warm during the chilly winter',
	'california': 'The popular drink in California is the Napa Valley Wine.',
	'colorado': 'The popular cocktail in Colorado is the colorado bulldog. The difference between a colorado bulldog and a white russian, you ask? The bulldog is bubbly, just like the peeps from Colorado.',
	'connecticut': 'The popular cocktail in Connecticut is the Dark \'N Stormy.',
	'delaware': 'The popular drink in Delaware is the Dogfish Head Ale.',
	'florida': 'The popular cocktail in Florida is the Rum Runner. No doubt that it is the perfect cocktail to sip while getting your tan on.', 
	'georgia': 'The popular cocktail in Georgia is the Scarlet O\'Hara.',
	'hawaii': 'The popular cocktail in hawaii is the Mai Tai. Mai Tai plus Hawaiian beaches equals heaven. Obviously',
	'idaho': 'The popular drink in Idaho is the Evan Williams Bourbon.',
	'illinois': 'The popular cocktail in Illinois is the J.G.&L. ',
	'indiana': 'The popular cocktail in Indiana is the Jägerbomb. These shots are fun to take, but don\'t drink too many of them.',
	'iowa': 'The popular cocktail in Iowa is the Templeton Rye, better known as the good stuff, one of iowa\'s finiest productions.',
	'kansas': 'The popular cocktail in Kansas is the Horsefeather. Think Moscow Mule, but whiskey instead of vodka. Oh, hell ya. this is something kansas should be proud of.',
	'kentucky': 'The popular cocktail in Kentucky is the Mint Julep.',
	'louisiana': 'The popular cocktail in Louisiana is the Sazerac. It came a about in a New Orleans apothecary way way back in 1838 as the world\'s first cocktail ever.',
	'maine': 'The popular cocktail in Maine is the Allen\'s Coffee Brandy and Milk, also know as the sombrero is a crucial staple in the diet of anyone who lives in Maine. ',
	'maryland': 'The popular cocktail in Maryland is the Black Eyed Susan.',
        'massachusetts': 'The popular cocktail in massachusetts is the Cape Codder. What is better than a basic as fuck vodka cranberry?',
	'michigan': 'The popular cocktail in Michigan is the Hummer.',
	'minnesota': 'The popular cocktail in Minnesota is the Bootleg, the happiest medium of a gin and tonic and a mojito.',
	'mississippi': 'The popular cocktail in Mississippi is the mississippi punch. This cocktail essentially mississippi history in a glass will get you drunk.',
	'missouri': 'The popular drink in Missouri is the Caribou Lou. It is a real hit.',
	'montana': 'The popular drink in Montana is the Whiskey Ditch. Quick english lesson: Ordering a drink followed by “ditch” means “with water.” Montanans don’t f*ck around when it comes to alcohol, so they obviously only use water as a mixer.',
	'nebraska': 'The popular drink in Nebraska is the founders brewing curmudgeon old ale.',
	'nevada': 'The popular cocktail in Nevada is the Nevada cocktail.',
	'new hampshire': 'The popular drink in New Hampshire is the fireball.',
	'new jersey': 'The popular cocktail in New Jersey is the Jack Rose. The people that live in the dirty Jerz are proud of their apples, so this cocktail incorporates applejack, grenadine and lemon juice.',
	'new mexico': 'The popular cocktail in New Mexico is the chimayo cocktail.',
        'new york': 'The popular cocktail in new york is the Long Island Iced Tea. Manhattan, definitely LIT. This heavy duty cocktail is what every New Yorker needs.',
	'north carolina': 'The popular cocktail in North Carolina is the Cherry Bounce. the cherry bounce is considered the official cocktail of the state\'s capital city.',

	'north dakota': 'The popular drink in North Dakota is the Fargo Brewing Company Iron Horse Pale Ale. Woah, North Dakota is one of the six states in the country that consumes over 40 gallons of beer per person over 21 per year.',
	'ohio': 'The popular cocktail in Ohio is the Buckeye Martini.',
	'oklahoma': 'The popular cocktail in Oklahoma is the bloody mary.',
	'oregon': 'The popular cocktail in Oregon is the Sloe Gin Fizz.',
	'pennsylvania': 'The popular drink in Pennsylvania is the Yuengling.',
	'rhode island': 'The popular cocktail in Rhode Island is the Rhode Island Red.',
	'south carolina': 'The popular cocktail in South Carolina is the firefly sweet tea. This spirit is a taste of southern hospitality at its finest.',
	'south dakota': 'The popular drink in South Dakota is the Bud Light.',
	'tennessee': 'The popular cocktail in Tennessee is the Moonshine.',
	'texas': 'The popular cocktail in Texas is the Frozen Margarita. In Dallas in 1971, Mariano Martinez made margs in a soft serve ice cream machine and called it “The World’s First Frozen Margarita Machine.” Over time, the frozen margarita has undoubtedly become the most popular cocktail in the entire state of Texas.',
	'utah': 'The popular drink in Utah is the Polygamy Nitro Porter. Utahns apparently really dig dark beers. You do you, Utah.',
	'vermont': 'The popular cocktail in Vermont is the Old Vermont, spotlighting the maple syrup that Vermont prides itself on.',
	'virginia': 'The popular drink in Virginia is any glass from virginia wine country. Wine, Virginia style, is what’s up.',
	'washington': 'The popular cocktail in Washington is the Washington Apple.',
	'west virginia': 'The popular cocktail in West Virginia is the copperhead.',
	'wisconsin': 'The popular cocktail in Brandy Old Fashioned. Wisconsinites don\'t fuck around with their Old Fashioned\'s. Most versions of this cocktail are made with whiskey, but if you’re in Wisconsin, the cocktail is made with a heavy pour of brandy.',
	'wyoming': 'The popular drink in Wyoming is the Franzia Chillable Red. For the least populated state in the country, it’s kind of shocking that people love boxed wine. hastage slap the bag.',
	'washington d.c.': 'The popular cocktail in Washington D.C. is the rickey.',
  },
};
